import { useState, useEffect, useRef, useMemo } from "react";
import { getInterviewResult } from "../Services/interviewService";

// ─── Tunables ─────────────────────────────────────────────────────────────────
export const POLL_INTERVAL_MS = 4000;   // how often we ask the server
export const POLL_TIMEOUT_MS  = 90000;  // hard stop — never poll forever
const MAX_CONSECUTIVE_ERRORS  = 5;      // give up early if the server is down
const BACKOFF_STEP_MS         = 2000;   // extra wait per consecutive error

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Feedback arrives as a JSON string from Mongo, but tolerate an object too.
export const parseFeedback = (raw) => {
  if (!raw) return null;
  try {
    const parsed = typeof raw === "string" ? JSON.parse(raw) : raw;
    return parsed && typeof parsed === "object" ? parsed : null;
  } catch {
    return null;
  }
};

// Only skipped, open-ended questions can ever be "pending".
const isPendingQuestion = (q) => {
  if (!q || !q.skipped) return false;
  if (["mcq", "aptitude"].includes(q.questionType)) return false;
  return parseFeedback(q.feedback)?.skippedPending === true;
};

// The polling endpoint returns { session: { questions } }. Be forgiving in case
// the shape ever changes to { questions } or a bare array.
const extractQuestions = (payload) => {
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload?.session?.questions)) return payload.session.questions;
  if (Array.isArray(payload?.questions)) return payload.questions;
  return [];
};

// ─── Hook ─────────────────────────────────────────────────────────────────────
//
// usePendingAnswers(sessionId, questions)
//
//   questions   the (normalized) questions the page already has. We only read
//               `id`, `skipped`, `questionType` and `aiFeedback.skippedPending`
//               from them to decide what is pending at mount time.
//
// Returns
//   pendingIds         Set<string>            ids still waiting on the server
//   resolvedOverrides  Map<string, object>    id -> { score, aiFeedback } for
//                                             answers that landed while polling
//   timedOut           boolean                true if we gave up while some
//                                             answers were still pending
//
// Why `timedOut` exists: the answer is generated by a fire-and-forget server
// job. If the server restarts mid-job (likely on a free-tier host) the flag
// `skippedPending` stays in the DB forever. Without a terminal state the UI
// would show "generating…" permanently.
export const usePendingAnswers = (sessionId, questions) => {
  const [pendingIds, setPendingIds]               = useState(() => new Set());
  const [resolvedOverrides, setResolvedOverrides] = useState(() => new Map());
  const [timedOut, setTimedOut]                   = useState(false);

  // Ids that were pending when we started. Computed once per session so that
  // re-renders (or retry overrides) never restart or extend the poll loop.
  const initialPendingRef = useRef(null);
  const startedForRef     = useRef(null);

  // A stable key describing which questions are pending right now. Using a
  // string means the effect only re-runs when the *set of pending ids*
  // changes, not on every render of the parent.
  const pendingKey = useMemo(() => {
    if (!Array.isArray(questions)) return "";
    return questions
      .filter((q) => q?.id && q.skipped && q.aiFeedback?.skippedPending === true &&
        !["mcq", "aptitude"].includes(q.questionType))
      .map((q) => q.id)
      .sort()
      .join("|");
  }, [questions]);

  useEffect(() => {
    // Nothing to do without a session or without pending questions.
    if (!sessionId || !pendingKey) return undefined;

    // Guard: only start one loop per session. A new session id resets it.
    if (startedForRef.current === sessionId && initialPendingRef.current) {
      return undefined;
    }
    startedForRef.current     = sessionId;
    initialPendingRef.current = new Set(pendingKey.split("|"));

    let cancelled     = false;
    let timerId       = null;
    let errorCount    = 0;
    const startedAt   = Date.now();
    const stillPending = new Set(initialPendingRef.current);

    setPendingIds(new Set(stillPending));
    setResolvedOverrides(new Map());
    setTimedOut(false);

    const finish = ({ timeout }) => {
      if (cancelled) return;
      if (timeout && stillPending.size > 0) setTimedOut(true);
      // Whatever is left can no longer be expected to resolve.
      setPendingIds(new Set());
    };

    const tick = async () => {
      if (cancelled) return;

      if (Date.now() - startedAt >= POLL_TIMEOUT_MS) {
        finish({ timeout: true });
        return;
      }

      let nextDelay = POLL_INTERVAL_MS;

      try {
        const payload   = await getInterviewResult(sessionId);
        if (cancelled) return;
        errorCount = 0;

        const serverQs  = extractQuestions(payload);
        const byId      = new Map(serverQs.map((q) => [q.id, q]));
        const newlyDone = new Map();

        stillPending.forEach((id) => {
          const serverQ = byId.get(id);
          if (!serverQ) return;
          if (isPendingQuestion(serverQ)) return;      // still generating

          const parsed = parseFeedback(serverQ.feedback);
          if (!parsed) return;                          // unreadable, keep waiting

          newlyDone.set(id, {
            score: Number(serverQ.score) || 0,
            aiFeedback: {
              score:        Number(serverQ.score) || 0,
              correct:      null,
              good:         parsed.good         || "",
              missing:      parsed.missing      || "",
              idealHint:    parsed.idealHint    || "",
              tip:          parsed.tip          || "",
              sampleAnswer: parsed.sampleAnswer || "",
              aiAvailable:  parsed.aiAvailable !== false,
              fallback:     parsed.fallback === true,
              skippedPending: false,
              tier:         parsed.tier || "full",
              locked:       parsed.locked || null,
            },
          });
        });

        if (newlyDone.size > 0) {
          newlyDone.forEach((_, id) => stillPending.delete(id));
          setResolvedOverrides((prev) => {
            const next = new Map(prev);
            newlyDone.forEach((val, id) => next.set(id, val));
            return next;
          });
          setPendingIds(new Set(stillPending));
        }

        if (stillPending.size === 0) {
          finish({ timeout: false });
          return;
        }
      } catch {
        if (cancelled) return;
        errorCount += 1;
        if (errorCount >= MAX_CONSECUTIVE_ERRORS) {
          finish({ timeout: true });
          return;
        }
        // Back off a little on each consecutive failure.
        nextDelay = POLL_INTERVAL_MS + errorCount * BACKOFF_STEP_MS;
      }

      if (!cancelled) timerId = setTimeout(tick, nextDelay);
    };

    // First check after one interval, not immediately: the data we were handed
    // is at most a moment old, so an instant fetch would almost never differ.
    timerId = setTimeout(tick, POLL_INTERVAL_MS);

    return () => {
      cancelled = true;
      if (timerId) clearTimeout(timerId);
      // Allow a clean restart if the effect re-runs (e.g. React StrictMode
      // double-invokes effects in development).
      startedForRef.current     = null;
      initialPendingRef.current = null;
    };
  }, [sessionId, pendingKey]);

  return { pendingIds, resolvedOverrides, timedOut };
};

export default usePendingAnswers;